# A small portion of traffic is directed to new env.
# both are serving the traffic.

apiVersion: apps/v1

kind: Deployment

metadata:
  name: main-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: frontend-c
      env: main

  template:
    metadata:
      labels:
        app: frontend-c
        env: main
    spec:
      containers:
      - name: alpha
        image: linuxacademycontent/ckad-nginx:1.0.0
        ports:
        - containerPort: 80


---

apiVersion: v1

kind: Service

metadata:
  name: canary-svc

spec:
  selector:
    app: frontend-c

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---


apiVersion: apps/v1

kind: Deployment

metadata:
  name: canary-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend-c
      env: canary

  template:
    metadata:
      labels:
        app: frontend-c
        env: canary
    spec:
      containers:
      - name: beta
        image: linuxacademycontent/ckad-nginx:canary
        ports:
        - containerPort: 80
