apiVersion: apps/v1

kind: Deployment

metadata: # of kind
 name: myapp-deploy
 labels: # it's not a list (no -)
  app: frontend-deploy

spec: # of deploy (replication + selector + template)
 replicas: 3

 selector:
  matchLabels: #of which label's pods should be selected.
   app: frontend 

 template: # it covers pod's metadata & spec (kind & apiVersion skipped.)
  metadata: # of pod
   name: alpha-pod #optional, as it assigns random name followed by kind metadata name.
   labels:
    app: frontend
    #env: prod
    #section: business
  spec:
   containers: # of pod
   - name: alpha-cont
     image: nginx
# Make sure, at least one label in the selector and template.metadata.labels fields match exactly.
#otherwise, it gives error,and don't create deployment.