apiVersion: v1

kind: Pod

metadata:
 name: init
 
spec:
 containers:
 - name: alpha
   image: nginx
 initContainers:
 - name: beta
   image: nginx
   command: ["sh", "-c", "sleep 60"]

#init container is not a multicontainer pod.