kind : Cluster #C Capital
apiVersion : kind.x-k8s.io/v1alpha4 #V Capital
name : ibtisam  #name of the cluster #always in small letter
nodes: # always plural
- role : control-plane
# image: specify the image name # image is optional.
#- role : control-plane
# image: specify the image name
- role : worker
# image: specify the image name
- role : worker
# image: specify the image name

#kind.x-k8s.io: This is the API group specific to Kind, which is used to manage Kubernetes clusters in Docker.
#v1alpha4: This is the version of the API in that group. "alpha" indicates it's an early version, so it might still be evolving.