#kubectl taint node ibtisam-worker flower=lily:NoSchedule --dry-run=client -o yaml > node-config.yaml

apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-08-22T06:34:51Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    cpu: large
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ibtisam-worker
    kubernetes.io/os: linux
  name: ibtisam-worker
  resourceVersion: "141379"
  uid: b604cebb-320b-4c86-9676-93c6a5979b3a
spec:
  podCIDR: 10.244.1.0/24
  podCIDRs:
  - 10.244.1.0/24
  providerID: kind://docker/ibtisam/ibtisam-worker
  taints:
  - effect: NoSchedule
    key: flower
    value: lily
status:
  addresses:
  - address: 172.18.0.2
    type: InternalIP
  - address: ibtisam-worker
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: 65739308Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 1924836Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 65739308Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 1924836Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2024-08-24T11:56:19Z"
    lastTransitionTime: "2024-08-22T06:34:51Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2024-08-24T11:56:19Z"
    lastTransitionTime: "2024-08-22T06:34:51Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2024-08-24T11:56:19Z"
    lastTransitionTime: "2024-08-22T06:34:51Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2024-08-24T11:56:19Z"
    lastTransitionTime: "2024-08-22T06:35:14Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/library/import-2024-05-13@sha256:d147453847b7c5b8c33045e54d6e0301edea08b5ae152e84b9b5cab377e20321
    - registry.k8s.io/kube-apiserver-amd64:v1.30.0
    - registry.k8s.io/kube-apiserver:v1.30.0
    sizeBytes: 89436130
  - names:
    - docker.io/library/import-2024-05-13@sha256:98e54aaf0614547ead5c0bd7df946f6eb58f0abf0386240df20565d9dd2a2e8d
    - registry.k8s.io/kube-proxy-amd64:v1.30.0
    - registry.k8s.io/kube-proxy:v1.30.0
    sizeBytes: 85930170
  - names:
    - docker.io/library/import-2024-05-13@sha256:9615dec64d132ce44d42c15d071da7477499ab2aa9a44ff073b8d85944949023
    - registry.k8s.io/kube-controller-manager-amd64:v1.30.0
    - registry.k8s.io/kube-controller-manager:v1.30.0
    sizeBytes: 83459912
  - names:
    - docker.io/library/nginx@sha256:447a8665cc1dab95b1ca778e162215839ccbb9189104c79d7ec3a81e14577add
    - docker.io/library/nginx:latest
    sizeBytes: 71026652
  - names:
    - docker.io/library/import-2024-05-13@sha256:06e68f241fc2e56756800474858d7b359f7cf4da31eddae316a342059c20c274
    - registry.k8s.io/kube-scheduler-amd64:v1.30.0
    - registry.k8s.io/kube-scheduler:v1.30.0
    sizeBytes: 63021384
  - names:
    - registry.k8s.io/etcd:3.5.12-0
    sizeBytes: 57236178
  - names:
    - docker.io/kodekloud/webapp-color@sha256:99c3821ea49b89c7a22d3eebab5c2e1ec651452e7675af243485034a72eb1423
    - docker.io/kodekloud/webapp-color:latest
    sizeBytes: 31777918
  - names:
    - gcr.io/kodekloud/customimage/my-kubernetes-dashboard@sha256:7d70abe342b13ff1c4242dc83271ad73e4eedb04e2be0dd30ae7ac8852193069
    - gcr.io/kodekloud/customimage/my-kubernetes-dashboard:latest
    sizeBytes: 31659887
  - names:
    - docker.io/library/ubuntu@sha256:8a37d68f4f73ebf3d4efafbcf66379bf3728902a8038616808f04e34a9ab63ee
    - docker.io/library/ubuntu:latest
    sizeBytes: 29710357
  - names:
    - docker.io/kindest/kindnetd:v20240202-8f1494ea
    sizeBytes: 27755257
  - names:
    - docker.io/kindest/local-path-provisioner:v20240202-8f1494ea
    sizeBytes: 19365409
  - names:
    - docker.io/library/nginx@sha256:208b70eefac13ee9be00e486f79c695b15cef861c680527171a27d253d834be9
    - docker.io/library/nginx:1.27.0-alpine
    sizeBytes: 18405128
  - names:
    - registry.k8s.io/coredns/coredns:v1.11.1
    sizeBytes: 18182961
  - names:
    - docker.io/kindest/local-path-helper:v20230510-486859a6
    sizeBytes: 3052318
  - names:
    - docker.io/kodekloud/throw-dice@sha256:9c70a0f907b99293885a9591b6162e9ec89e127937626a97ca7f9f6be2d98b01
    - docker.io/kodekloud/throw-dice:latest
    sizeBytes: 2209939
  - names:
    - docker.io/library/busybox@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7
    - docker.io/library/busybox:latest
    sizeBytes: 2160406
  - names:
    - registry.k8s.io/pause:3.7
    sizeBytes: 311278
  nodeInfo:
    architecture: amd64
    bootID: d3d6e3dc-72a8-4ef2-9505-a8a3224e76f7
    containerRuntimeVersion: containerd://1.7.15
    kernelVersion: 6.6.32-linuxkit
    kubeProxyVersion: v1.30.0
    kubeletVersion: v1.30.0
    machineID: 374ec9be29b64124aabc29428f4d9146
    operatingSystem: linux
    osImage: Debian GNU/Linux 12 (bookworm)
    systemUUID: 374ec9be29b64124aabc29428f4d9146
