kind: Pod #always first letter capital

apiVersion: v1

metadata: # metadata for kind (pod)
  name: first-pod #lower case all, no space allowed
# namespace: your desised namespace
  labels: #optional
    app: frontend
    version: "1.0" #double quote the numeric values

spec:  #mandatory, add the containers
  
  containers:
  - name: first-cont
    image: nginx:1.27.0-alpine
    command: [ "sleep" ] #entrypoint
    args: [ "1000" ] #CMD

  restartPolicy: Never

  tolerations:
  - key: flower
    operator: Equal
    value: rose
    effect: NoSchedule

#toleration only works if node is tainted.