apiVersion: apps/v1

kind: ReplicaSet #R S, no space

metadata: # of rs
 name: myapp-rs
 labels: # it's not a list (no -)
  app: frontend-rs

spec: # of rs (replication + selector + template)
 replicas: 5

 selector:
  matchLabels: #of which label's pods should be selected.
   app: frontend # line 15 & 21 should match each other.

 template: # it covers pod's metadata & spec (kind & apiVersion skipped.)
  metadata: # of pod
   name: alpha-pod #optional, as it assigns random name followed by kind metadata name.
   labels:
    app: frontend
  spec:
   containers: # of pod
   - name: alpha-cont
     image: nginx
# Make sure the labels in the selector and template.metadata.labels fields match exactly.