apiVersion: v1

kind: ReplicationController #R C no space

metadata: # of rc
 name: myapp-rc
 labels: # it's not a list (no -)
  app: frontend-rc

spec: # of rc (replication + selector + template)
 replicas: 3

 selector:
  app: frontend # line 14 & 20 should match each other.

 template: # it covers pod's metadata & spec (kind & apiVersion skipped.)
  metadata: # of pod
   name: alpha-pod #optional, as it assigns random name followed by kind metadata name.
   labels:
    app: frontend
  spec:
   containers: # of pod
   - name: alpha-cont
     image: nginx

# Make sure the labels in the selector and template.metadata.labels fields match exactly.