apiVersion: v1

kind: Pod

metadata:
  name: webapp-pod
  namespace: default
  labels:
    name: webapp-pod
spec:
  containers:
  - name: webapp
    image: kodekloud/simple-webapp-mysql
    envFrom:
    - secretRef:
        name: db-secret #take care of indentation

---

apiVersion: v1

kind: Service

metadata:
  labels:
    name: webapp-pod
  name: webapp-pod-svc

spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    name: webapp-pod
  type: NodePort #because people will access it


---

apiVersion: v1

kind: Pod

metadata:
  name: mysql
  namespace: default
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password123
    ports:
    - containerPort: 3306 #mysql port
      protocol: TCP

---


apiVersion: v1

kind: Service

metadata:
  labels:
    name: mysql
  name: sq101
  namespace: default

spec:
  ports:
  - port: 3306 #where mysql listens
    protocol: TCP
    targetPort: 3306 #if one accesses this service, then this service redirects the traffic to which port
  selector: #if one accesses this service, then this service redirects the traffic to which pod
    name: mysql
  type: ClusterIP