apiVersion: v1

kind: Pod

metadata:
  name: test-pod-1

spec:
  containers:
  - name: test-cont-1
    image: ubuntu
    command: [ "sleep", "5000" ]


---

apiVersion: v1 #inside container

kind: Pod

metadata:
  name: test-pod-2

spec:
  containers:
  - name: test-cont-2
    image: ubuntu
    command: [ "sleep", "5000" ]
    securityContext:
      runAsUser: 1002

#whoami: cannot find name for user ID 1002
#command terminated with exit code 1

---

apiVersion: v1

kind: Pod             #at pod level also

metadata:
  name: test-pod-3

spec:
  securityContext:      #at pod level
    runAsUser: 1000
  containers:
  - name: test-cont-3
    image: ubuntu
    command: [ "sleep", "5000" ]
    securityContext:    #at container level
      runAsUser: 1003

#whoami: cannot find name for user ID 1003
#command terminated with exit code 1

---

apiVersion: v1

kind: Pod             

metadata:
  name: test-pod-m4

spec:
  securityContext:      #at pod level
    runAsUser: 1000
  containers:
  - name: test-cont-4
    image: ubuntu
    command: [ "sleep", "5000" ]
    securityContext:    #at first container level
      runAsUser: 1004
      capabilities:     # supported at container level only, not at pod level
        add:  #add is an array.
        - 

#whoami: cannot find name for user ID 1004
#command terminated with exit code 1

  - name: test-cont-5  # not at this container level, 
    image: ubuntu       # so it will use pod level security context by-default.
    command:
    - "sleep"
    - "5000"