#kubectl create sa dashboard-sa -o yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2024-08-24T06:46:47Z"
  name: dashboard-sa
  namespace: default
  resourceVersion: "115758"
  uid: 5559ab53-6135-44f6-8f5f-2e935d78900f

---

apiVersion: rbac.authorization.k8s.io/v1

kind: Role #this role will bind to the service account

metadata:
  namespace: default
  name: pod-reader

rules:
- apiGroups:
  - ''
  resources: #mention these resources of which details you want to fetch like pods,deployments etc
  - pods
  verbs: #actions
  - get 
  - watch
  - list

#role is created, but it can't do anything.
# until you bind it with an object, called RoleBinding 
---

apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: read-pod
  namespace: default

subjects:
- kind: ServiceAccount #which rerource is being bound # line 4
  name: dashboard-sa    # name of that resource being bound
  namespace: default

roleRef:
  kind: Role
  name: pod-reader # must match with role name
  apiGroup: rbac.authorization.k8s.io




---
apiVersion: v1

kind: Pod

metadata:
  name: my-dashboard
  labels:
    app: dashboard

spec:
  containers:
  - name: web-dashboard
    image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: PYTHONUNBUFFERED
      value: "1"


---

apiVersion: v1 # copied from IC
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dashboard
  name: dashboard
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dashboard
  type: NodePort
status:
  loadBalancer: {}
