kind: Pod

apiVersion: v1

metadata: 
  name: sam
  namespace: default
  labels:
    app: frontend

spec:
  
  containers:
  - name: sam
    image: nginx:1.27.0-alpine
    command: [ "sleep" ] #entrypoint
    args: [ "1000" ] #CMD

  restartPolicy: Never

  tolerations:
  - key: flower
    operator: Equal #if Exits, no value. # Equal & Exits
    value: rose #value not values
    effect: NoSchedule
  

#toleration only works if node is tainted.

# nodeSelector: #pod schedular will check all nodes labels before its scheduling.
#   cpu: large  #schedule a specific pod on a specific node

# concept of nodeAffinity comes into picture when nodeSelector does not serve the purpose.

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # preferredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - antarctica-east1
            - antarctica-west1