# kind-cluster-config.yaml

apiVersion: kind.x-k8s.io/v1alpha4   # Specifies the Kind API version to use
kind: Cluster                        # Declares that this is a Kind Cluster configuration
name: ibtisam
nodes:                               # Declares the nodes section to define multiple nodes in the cluster
  - role: control-plane              # Defines the first node as a control-plane (master) node
    image: kindest/node:v1.30.0      # Specifies the container image for the control-plane node (Kubernetes version v1.24.0)

  - role: control-plane              # Defines the second node as a control-plane (master) node
    image: kindest/node:v1.30.0      # Uses the same Kubernetes version for uniformity

  - role: worker                     # Defines the first worker node
    image: kindest/node:v1.30.0      # Specifies the Kubernetes version for the worker node

  - role: worker                     # Defines the second worker node
    image: kindest/node:v1.30.0      # Uses the same Kubernetes version for the worker node

---


