# kind-cluster-config.yaml

apiVersion: kind.x-k8s.io/v1alpha4   # Specifies the Kind API version to use
kind: Cluster                        # Declares that this is a Kind Cluster configuration
name: ibtisam
nodes:                               # Declares the nodes section to define multiple nodes in the cluster
  - role: control-plane              # Defines the first node as a control-plane (master) node
    image: kindest/node:v1.30.0      # Specifies the container image for the control-plane node (Kubernetes version v1.24.0)
#   extraPortMappings:               # Optional: Maps extra ports on the host to ports on the node
#     - containerPort: 30000         # Maps container port 30000
#       hostPort: 8080               # to host port 8080
#       protocol: TCP                # Protocol used (TCP)
#   kubeadmConfigPatches:            # Optional: Custom Kubeadm configurations
#     - |
#       kind: InitConfiguration
#       nodeRegistration:
#         name: control-plane-1      # Name of the control plane node 1
  - role: control-plane              # Defines the second node as a control-plane (master) node
    image: kindest/node:v1.30.0      # Uses the same Kubernetes version for uniformity
#   kubeadmConfigPatches:            # Custom Kubeadm configurations
#     - |
#       kind: JoinConfiguration
#       nodeRegistration:
#         name: control-plane-2      # Name of the control plane node 2
  - role: worker                     # Defines the first worker node
    image: kindest/node:v1.30.0      # Specifies the Kubernetes version for the worker node
#   kubeadmConfigPatches:            # Optional: Patches for worker-specific configuration
#     - |
#       kind: JoinConfiguration
#       nodeRegistration:
#         name: worker-1             # Name of the worker node 1
  - role: worker                     # Defines the second worker node
    image: kindest/node:v1.30.0      # Uses the same Kubernetes version for the worker node
#   kubeadmConfigPatches:            # Custom patches for this node as well
#     - |
#       kind: JoinConfiguration
#       nodeRegistration:
#         name: worker-2             # Name of the worker node 2

#networking:                          # Networking configuration block
# disableDefaultCNI: false           # Default CNI (Container Network Interface) is enabled
# podSubnet: "10.244.0.0/16"         # Pod network IP address range
# serviceSubnet: "10.96.0.0/12"      # Service network IP address range
# apiServerAddress: "127.0.0.1"      # The IP address to bind the API server to (localhost)
# apiServerPort: 6443                # Port for the API server (default is 6443)

#kubeadmConfigPatches:                # Global kubeadm config patches (applied to all nodes)
# - |
#   kind: ClusterConfiguration
#   apiServer:
#     extraArgs:
#       authorization-mode: Node,RBAC # Enables Node and Role-Based Access Control (RBAC) authorization modes

#featureGates:                        # Optional feature gates for enabling/disabling Kubernetes features
# IPv6DualStack: true                # Enables dual-stack IPv4/IPv6 support

#containerdConfigPatches:             # Custom patches for containerd (optional)
# - |
#   [plugins."io.containerd.grpc.v1.cri".containerd]
#     snapshotter = "overlayfs"
