apiVersion: v1
kind: Pod             # Single container pod
metadata:
  labels:
    run: abc                    #if not mentined, if picks the name of Pod # not mandatory
  name: abc                     # mandatory
spec:
  containers:
  - image: nginx
    name: abc
---
apiVersion: v1
kind: Pod             # Init container pod
metadata:
  name: init
spec:
  containers:
  - name: alpha
    image: nginx
  initContainers:                            # init container is not a multi-container pod.
  - name: beta                               # it's also a list, you can have multiple initContainers.
    image: nginx
    command: ["sh", "-c", "sleep 60"]

---
apiVersion: v1
kind: Pod           #  SideCar Multi-container pod
metadata:
  name: sidecar-container
spec:
  containers:
  - name: main-container
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  - name: sidecar-container
    image: busybox
    command: ['sh', '-c', 'echo "this is ibtisam"; while true; do sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /pod-data
  volumes:
  - name: shared-volume
    emptyDir: {}

---

apiVersion: v1
kind: Pod         # Ambassador Multi-container pod
metadata:
  name: test-pod
spec:
  containers:
  - name: abcd
    image: busybox