apiVersion: v1
kind: Namespace
metadata:
  name: ibtisam
spec: {}
status: {}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: abc-ns-rq
  namespace: ibtisam
spec:
  hard:                           # max served capacity # specifies the hard/max limits for each resource
    cpu: "2"
    memory: 5Gi
    pods: "10"
    services: "5"
    persistentvolumeclaims: "2"
    
status: {}

---
# - CPU is measured in millicores (1 core = 1000m).
# - Memory is measured in bytes (you can use suffixes like Ki, Mi, Gi for kilobytes, megabytes, and gigabytes).
apiVersion: v1
kind: Pod
metadata:
  name: abc
  namespace: ibtisam
spec:
  containers:
  - image: nginx
    name: abc   
    resources:            # Resource requests and limits help with resource management in Kubernetes.
      limits:             # Limits define the maximum amount of resources the container can use.
        cpu: "1.5"        # The maximum CPU the container can consume.
        memory: 3Gi       # The maximum memory the container can consume.
      requests:           # Requests define the amount of resources the container is guaranteed to have.
        cpu: "1"          # The minimum CPU the container requires.
        memory: 1.5Gi     # The minimum memory the container requires.

# if a pod is created with a resource request that exceeds the quota, 
# the pod will not be created (showing pending status), and an error will be returned.

# So, replace that pod. 
# kubectl edit doesn't work here, so we have to delete the pod and recreate it.