apiVersion: v1
kind: Pod
metadata:
  name: sec-con-po-0
spec:
  containers:
  - name: cont-0
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: sec-con-po-1
spec:
  containers:
  - name: cont-1
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1001
---
apiVersion: v1
kind: Pod
metadata:
  name: sec-con-po-2
spec:
  securityContext:            # at pod level # Applied to all containers in the Pod.
    runAsUser: 1000           # Ensures that all containers in the Pod run as a non-root user with UID 1000.
    runAsGroup: 2000          # All containers will use this group (GID 2000).
    fsGroup: 3000             # Ensures that any volumes mounted by the Pod will have group ownership of 3000. 
    # Filesystems inside the Pod will be owned by this group ID.
    seLinuxOptions:           # SELinux options, useful for added security in SELinux-enabled clusters.
      level: "s0:c123,c456"
  containers:
  - name: sec-con-cont-1
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1002           
      runAsGroup: 2002          
    # fsGroup: 3002                    # Not applied at container level
      allowPrivilegeEscalation: false  # Ensures that no process within the container can gain more privileges.
      capabilities:
        add:                           # Add Linux capabilities to the container.
        - NET_ADMIN                    # Grants network-related capabilities to modify networking parameters.
        - SYS_TIME                     # Allows the container to change the system clock.
        drop:                          # Drop capabilities that the container does not need.
        - MKNOD                        # Prevent the container from creating special files like device nodes.
      runAsNonRoot: true               # Enforces the container to run as a non-root user.
      readOnlyRootFilesystem: true     # Enforces the container's root filesystem to be read-only. 
      # This is useful for security and prevents the container from modifying its own filesystem.
      # Locks the container's root filesystem to be read-only, enhancing security.
  - name: sec-con-cont-2
    image: busybox
    command: ["sleep", "3600"]

# Security Context at Pod level implements to all Pod's containers.
# Security Context at Container level implements to that specific container only.
# If you define both, the container level will override the Pod level. 