apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: abcd
    image: busybox
    command: ["sleep"]
    args: ["3600"]

---

apiVersion: v1
kind: Pod
metadata:
  name: com-arg-5-1
spec:
  containers:
  - name: com-arg-busybox-5-1
    image: busybox
#   command: ['sh', '-c', 'echo $PWD', 'ls -l /etc/os-release', 'cat /etc/os-release', 'sleep 3600'] # incorrect
    command: ["sh", "-c", "echo $PWD && sleep 3600"]